# Generated by Django 5.2.1 on 2025-05-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_wishlist_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
